### ISSUE TITLE
Design Commentary

### ISSUE THREAD

**Issue by thelifeandtimes** [deathtothecorporation/vaporware.network#2]
## General
- Desktop -> Mobile breakpoint is 801 -> 800px viewport
#### TODO
- [ ] clean up typography sheet with actuals
- [ ] play with max/min width feature
- [ ] check all the spacing is consistent across page designs
- [ ] clean up
	- [ ] labeling
	- [ ] pages
	- [ ] components
	- [ ] sections
- [ ] Add Detail Frames
	- [ ] hamburger menu
	- [ ] virtual keyboard for form entry
- [ ] Build out prototypes?
	- [ ] click through
	- [ ] Animations
	- [ ] Menu toggles?
- [ ] Hover and Selection States for nav / buttons
- [ ] activity updates form/button at max width on mobile (800px) is centered/weird
	- [ ] probably play with autolayout wrapping
### Mobile
- Nav bar disappears on downward scroll, reappears on upwards scroll
- 24 pixel gutters
### Desktop
- Nav bar and footer bar should go full width even on ultrawide screens
## Homepage
- Full bleed image / gif should pull random file from repository, ideally checking requesting IP and serving something never before seen by that IP.
### Mobile 
- No scrolling
- Form and Copy Block indexed off bottom
- On form selection, Form and copy block should shift upwards to allow for virtual keyboard
### Desktop
- No scrolling
- Max width of 1280 pixels for text and form div

## Blog Index
- Transparent navigation bar
#### TODO
- [ ] Establish Auto Layouts
### Mobile
- Side scrolling inventory of 'cards' on mobile
- Side scroll should 'snap' such that when you release your finger the 'focused' card indexes to the starting location on the screen
### Desktop
- Nav bar pinned to top on scroll
- Full bleed background image with parallax scrolling
## Blog Template
- black navigation bar
### Desktop
- Nav bar disappears on downward scroll, reappears on upwards scroll
## Experiments Index
- Transparent Navigation Bar

### Mobile
- background image should be full bleed, fitting to top / bottom of viewport
### Desktop
- Background image should be full bleed, fitting to left / right of viewport
## Experiments Template
- Transparent Navigation Bar
#### TODO
- [ ] experiments template
	- [ ] desktop
	- [ ] mobile
### Mobile
- header image should be square, based on viewport width
### Desktop
- Nav bar disappears on downward scroll, reappears on upwards scroll
